# Generated by Django 5.2.5 on 2025-08-17 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'email')},
        ),
    ]
