# Generated by Django 5.2.5 on 2025-08-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_event_email'),
        ),
    ]
