# Generated by Django 5.2.5 on 2025-08-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participant',
            name='unique_event_email',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('event', 'email')},
        ),
    ]
